# Generated by Django 4.2.1 on 2023-05-21 01:11

from django.db import migrations
import users.my_models.miscellaneous


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_permission_is_shepherd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=users.my_models.miscellaneous.OutdatedDateField(blank=True, max_length=200, null=True),
        ),
    ]
