# Generated by Django 4.2.1 on 2023-05-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_catalog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_year_of_study',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Current Year of Study'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='years_of_study',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No of Years of Study'),
        ),
    ]
