# Generated by Django 4.2.1 on 2023-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_current_year_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chronic_illness',
            field=models.CharField(blank=True, help_text='please specify', max_length=200, null=True, verbose_name='Any Chronic Ailment'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='final_year_status',
            field=models.CharField(blank=True, help_text='Update when appropriate', max_length=255, null=True, verbose_name='Final Year Status'),
        ),
    ]
