# Generated by Django 4.2.1 on 2023-06-07 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.OneToOneField(default='senai', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, help_text='separate skills with comma. eg., writing, voice over', max_length=1000, null=True, verbose_name='Skills'),
        ),
    ]
