# Generated by Django 4.2.1 on 2023-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strict_report',
            field=models.CharField(choices=[('None', 'None'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednessday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='None', max_length=20),
        ),
    ]
