# Generated by Django 4.2.5 on 2023-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_strict_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='meta_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
