# Generated by Django 4.2.7 on 2023-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_catalog_meta_information'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='full_name_constraints'),
        ),
    ]
