# Generated by Django 4.2.7 on 2023-12-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_customuser_full_name_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
