# Generated by Django 4.2.7 on 2023-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_graduate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduate_status',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=15, null=True, verbose_name='Graduate Status'),
        ),
    ]
