# Generated by Django 4.2.7 on 2024-01-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_weekthree_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekthree',
            name='exception',
            field=models.BooleanField(default=False),
        ),
    ]
