# Generated by Django 4.2.7 on 2024-02-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_weekthree_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_status',
            field=models.TextField(blank=True, choices=[('employed', 'Employed'), ('employed_but_still_looking', 'Employed but still looking for another job'), ('under_employed', 'Under Employed'), ('unemployed', 'Unemployed')], null=True, verbose_name='Employment Status'),
        ),
    ]
