# Generated by Django 4.2.7 on 2024-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_customuser_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('sngle', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow')], max_length=10, null=True, verbose_name='Marital Status'),
        ),
    ]
