# Generated by Django 4.2.7 on 2024-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_customuser_church_outpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='short_link_manager',
            field=models.BooleanField(default=False),
        ),
    ]
