# Generated by Django 5.1.7 on 2025-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='gam_admin_level',
            field=models.BooleanField(default=False),
        ),
    ]
