# Generated by Django 4.2.6 on 2023-10-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('department_name',), 'verbose_name_plural': 'Department Members'},
        ),
    ]
