# Generated by Django 4.2.6 on 2023-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_departmentmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='member_names',
            field=models.ManyToManyField(to='project_management.departmentmember'),
        ),
    ]
