# Generated by Django 4.2.6 on 2023-10-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_alter_department_member_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='member_names',
            field=models.ManyToManyField(blank=True, to='project_management.departmentmember'),
        ),
    ]
