# Generated by Django 4.2.6 on 2023-10-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0013_departmentcategory_department_department_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
