# Generated by Django 4.2.6 on 2023-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_rename_category_departmentcategory_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmember',
            options={'verbose_name_plural': 'Department Members'},
        ),
    ]
