# Generated by Django 4.2.6 on 2023-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_alter_departmentmember_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='gmt',
            name='target',
        ),
        migrations.AddField(
            model_name='gmt',
            name='target',
            field=models.ManyToManyField(to='project_management.categorytarget'),
        ),
    ]
