# Generated by Django 4.2.6 on 2023-10-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_categorytarget_remove_gmt_target_gmt_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytarget',
            options={'verbose_name_plural': 'Category Targets'},
        ),
    ]
