# Generated by Django 4.2.6 on 2023-10-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_alter_categorytarget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmt',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.department'),
            preserve_default=False,
        ),
    ]
