# Generated by Django 4.2.6 on 2023-10-31 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_gmt_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMTProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000)),
                ('project_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.department')),
                ('department_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.departmentcategory')),
                ('project_members', models.ManyToManyField(blank=True, to='project_management.departmentmember')),
            ],
            options={
                'verbose_name_plural': 'GMT Projects',
                'ordering': ('due_date',),
            },
        ),
        migrations.RenameModel(
            old_name='RedChairTruth',
            new_name='ArchiversProject',
        ),
        migrations.RenameModel(
            old_name='Archivers',
            new_name='CatalogueProject',
        ),
        migrations.RenameModel(
            old_name='Catalogue',
            new_name='ExtractionProject',
        ),
        migrations.RenameModel(
            old_name='Website',
            new_name='RedChairTruthProject',
        ),
        migrations.RenameModel(
            old_name='Extraction',
            new_name='WebsiteProject',
        ),
        migrations.DeleteModel(
            name='GMT',
        ),
    ]
