# Generated by Django 4.2.6 on 2023-10-31 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_gmtproject_rename_redchairtruth_archiversproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000)),
                ('project_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.department')),
                ('department_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.departmentcategory')),
                ('project_members', models.ManyToManyField(blank=True, to='project_management.departmentmember')),
            ],
            options={
                'verbose_name_plural': 'Department Projects',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.departmentproject')),
            ],
            options={
                'verbose_name_plural': 'Project Targets',
            },
        ),
        migrations.DeleteModel(
            name='ArchiversProject',
        ),
        migrations.DeleteModel(
            name='CatalogueProject',
        ),
        migrations.DeleteModel(
            name='CategoryTarget',
        ),
        migrations.DeleteModel(
            name='ExtractionProject',
        ),
        migrations.RemoveField(
            model_name='gmtproject',
            name='about',
        ),
        migrations.RemoveField(
            model_name='gmtproject',
            name='department_category',
        ),
        migrations.RemoveField(
            model_name='gmtproject',
            name='project_members',
        ),
        migrations.DeleteModel(
            name='RedChairTruthProject',
        ),
        migrations.DeleteModel(
            name='WebsiteProject',
        ),
        migrations.DeleteModel(
            name='GMTProject',
        ),
        migrations.AddField(
            model_name='departmentproject',
            name='target',
            field=models.ManyToManyField(blank=True, to='project_management.projecttarget'),
        ),
    ]
