# Generated by Django 4.2.6 on 2023-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_departmentproject_projecttarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentproject',
            name='project_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
