# Generated by Django 4.2.6 on 2023-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0023_projecttarget_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
