# Generated by Django 4.2.6 on 2023-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0024_alter_departmentcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='departmentcategory',
            constraint=models.UniqueConstraint(fields=('category_name', 'department_name'), name='category_constraints'),
        ),
    ]
