# Generated by Django 4.2.6 on 2023-11-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0025_alter_departmentcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttarget',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
