# Generated by Django 4.2.6 on 2023-11-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0027_remove_projecttarget_completed_projecttarget_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentproject',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_management.departmentmember'),
        ),
    ]
