# Generated by Django 4.2.6 on 2023-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0028_departmentproject_project_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_objectives',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Turpis viverra viverra mollis sed vitae fames nunc sollicitudin viverra. Curabitur massa, ultrices diam ipsum faucibus risus. Hendrerit justo, quis massa a elementum. At elementum.'),
            preserve_default=False,
        ),
    ]
