# Generated by Django 4.2.6 on 2023-11-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0029_department_department_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcategory',
            name='category_objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
