# Generated by Django 4.2.7 on 2023-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0030_departmentcategory_category_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmember',
            name='love',
            field=models.TextField(default='ljo'),
            preserve_default=False,
        ),
    ]
