# Generated by Django 4.2.7 on 2023-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0033_departmentmember_members_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentproject',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
