# Generated by Django 4.2.7 on 2023-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0034_alter_departmentproject_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmember',
            name='experience_score',
            field=models.IntegerField(default=0),
        ),
    ]
