# Generated by Django 4.2.7 on 2023-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0035_departmentmember_experience_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttarget',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='state',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Pending Approval', 'Pending Approval')], default='Not Started', max_length=25),
        ),
    ]
