# Generated by Django 4.2.7 on 2023-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0036_projecttarget_is_approved_alter_projecttarget_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttarget',
            name='state',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending Approval', 'Pending Approval')], default='Not Started', max_length=25),
        ),
    ]
