# Generated by Django 4.2.7 on 2023-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0037_alter_projecttarget_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttarget',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='department',
            name='department_long_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Department (Long Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('GMT', 'GMT'), ('Extraction', 'Extraction Team'), ('Website', 'Website Team'), ('Archive', 'Archive')], max_length=255, unique=True, verbose_name='Department (Short Name)'),
        ),
    ]
