# Generated by Django 4.2.7 on 2023-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0038_remove_projecttarget_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_long_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Department (Long Name)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('GMT', 'GMT'), ('Extraction', 'Extraction Team'), ('Website', 'Website Team'), ('Archive', 'Archive'), ('GRT', 'GRT')], max_length=255, unique=True, verbose_name='Department (Short Name)'),
        ),
    ]
