# Generated by Django 4.2.7 on 2023-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0039_alter_department_department_long_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Department (Short Name)'),
        ),
    ]
