# Generated by Django 4.2.7 on 2023-11-26 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0044_alter_departmentproject_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDepartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reasons', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.department')),
            ],
        ),
    ]
