# Generated by Django 4.2.7 on 2023-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0045_pendingdepartmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentproject',
            name='project_background_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departmentproject',
            name='project_text_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departmentproject',
            name='project_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
