# Generated by Django 4.2.7 on 2023-12-04 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0046_departmentproject_project_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('table_name_plural', models.CharField(max_length=255)),
                ('table_description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.department')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
