# Generated by Django 4.2.7 on 2023-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0047_departmenttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttable',
            name='table_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
