# Generated by Django 4.2.7 on 2023-12-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0048_alter_departmenttable_table_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttable',
            options={'ordering': ('-date',), 'verbose_name_plural': "Department's Table"},
        ),
    ]
