# Generated by Django 4.2.7 on 2023-12-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0050_customfield_fieldvalue_customfield_values_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttable',
            options={'ordering': ('-date',), 'verbose_name_plural': "Department's Tables"},
        ),
    ]
