# Generated by Django 4.2.7 on 2023-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0051_alter_departmenttable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttable',
            name='fields',
            field=models.ManyToManyField(blank=True, to='project_management.customfield'),
        ),
    ]
