# Generated by Django 4.2.7 on 2023-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0052_alter_departmenttable_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmenttable',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='department',
            name='custom_tables',
            field=models.ManyToManyField(blank=True, to='project_management.departmenttable'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='foreign_key',
            field=models.CharField(blank=True, help_text='Know which other it links to', max_length=255, null=True),
        ),
    ]
