# Generated by Django 4.2.7 on 2023-12-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0053_rename_department_departmenttable_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='conditions',
            field=models.TextField(blank=True, help_text='contains code that will executed with eval', null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='value',
            field=models.TextField(blank=True, help_text='use custom field definition to enforce constraints', null=True),
        ),
    ]
