# Generated by Django 4.2.7 on 2023-12-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0054_alter_customfield_conditions_alter_fieldvalue_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValueIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.departmenttable')),
                ('table_field_value', models.ManyToManyField(blank=True, to='project_management.fieldvalue')),
            ],
        ),
    ]
