# Generated by Django 4.2.7 on 2024-01-19 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0056_departmenttable_row_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_management.departmentmember')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.departmentmember')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_management.departmentmember')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.departmentmember')),
                ('sub_units', models.ManyToManyField(blank=True, to='project_management.subunit')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project_management.departmentmember')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_head', to='project_management.departmentmember')),
                ('members', models.ManyToManyField(blank=True, to='project_management.departmentmember')),
            ],
        ),
        migrations.AddField(
            model_name='subunit',
            name='teams',
            field=models.ManyToManyField(blank=True, to='project_management.team'),
        ),
        migrations.CreateModel(
            name='Episcopate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, to='project_management.department')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
