# Generated by Django 4.2.7 on 2024-01-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0057_subunit_unit_team_subunit_teams_episcopate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='unit_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_management.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sub_unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_management.subunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_management.department'),
            preserve_default=False,
        ),
    ]
