# Generated by Django 4.2.7 on 2024-01-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0059_alter_episcopate_assistant_alter_episcopate_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='episcopates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.episcopate'),
        ),
    ]
