# Generated by Django 4.2.7 on 2024-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0060_department_episcopates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
