# Generated by Django 4.2.7 on 2024-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0061_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episcopate',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
