# Generated by Django 4.2.7 on 2024-01-27 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0062_alter_episcopate_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episcopate',
            new_name='Diaconate',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='episcopates',
            new_name='department_diaconate',
        ),
    ]
