# Generated by Django 4.2.7 on 2024-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0063_rename_episcopate_diaconate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='department',
            new_name='unit_department',
        ),
        migrations.AddField(
            model_name='department',
            name='department_unit',
            field=models.ManyToManyField(blank=True, to='project_management.unit'),
        ),
    ]
