# Generated by Django 4.2.7 on 2024-02-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0064_rename_department_unit_unit_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_unit',
            new_name='department_units',
        ),
    ]
