# Generated by Django 4.2.7 on 2024-02-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0065_rename_department_unit_department_department_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_units',
        ),
    ]
