# Generated by Django 4.2.7 on 2024-03-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0067_rename_assistant_unit_sub_leader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='info',
            new_name='objective',
        ),
    ]
