# Generated by Django 4.2.7 on 2024-03-10 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0068_rename_info_unit_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentproject',
            name='department_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.departmentcategory'),
        ),
    ]
