# Generated by Django 5.1.7 on 2025-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0069_alter_departmentproject_department_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('password', 'password'), ('textarea', 'textarea'), ('email', 'email'), ('number', 'number'), ('checkbox', 'checkbox'), ('tel', 'tel'), ('url', 'url'), ('date', 'date'), ('time', 'time'), ('file', 'file'), ('search', 'search'), ('range', 'range'), ('color', 'color'), ('month', 'month'), ('week', 'week'), ('datetime-local', 'datetime-local')], max_length=255),
        ),
    ]
