# Generated by Django 5.1.7 on 2025-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0070_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_objectives',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
