# Generated by Django 4.2.6 on 2023-10-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propheticword',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Prophetic Words'},
        ),
    ]
