# Generated by Django 4.2.6 on 2023-10-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0002_alter_propheticword_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
