# Generated by Django 4.2.6 on 2023-10-26 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0003_delete_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('testifier', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('life', 'Life Testimony'), ('general', 'General Testimony'), ('evangelism', 'Evangelism Testimony')], max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ('-date',),
            },
        ),
    ]
