# Generated by Django 4.2.7 on 2023-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0007_alter_sermon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='propheticword',
            name='ai_generated_keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
