# Generated by Django 4.2.7 on 2023-12-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0008_propheticword_ai_generated_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='propheticword',
            name='ai_generated_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propheticword',
            name='ai_generated_keywords',
            field=models.TextField(blank=True),
        ),
    ]
