# Generated by Django 4.2.7 on 2024-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0009_propheticword_ai_generated_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propheticword',
            name='ai_generated_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propheticword',
            name='ai_generated_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
