# Generated by Django 4.2.7 on 2024-07-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pastoring.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastoring', '0010_alter_propheticword_ai_generated_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(blank=True, max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_alias', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, pastoring.models.Utility),
        ),
    ]
