# Generated by Django 4.2.7 on 2024-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0011_urlshortener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortener',
            name='custom_alias',
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
