# Generated by Django 4.2.7 on 2024-07-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastoring', '0012_remove_urlshortener_custom_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='original_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
