# Generated by Django 4.2.7 on 2024-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0013_urlshortener_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='original_url',
            field=models.URLField(unique=True),
        ),
    ]
