# Generated by Django 4.2.7 on 2024-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoring', '0015_alter_urlshortener_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
