# Generated by Django 4.2.1 on 2023-06-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_permission_name_alter_customuser_skills'),
        ('home', '0003_birthdaymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionComplaintMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Complaint', 'Complaint')], max_length=15)),
                ('level_of_urgency', models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Critical', 'Critical'), ('Emergency', 'Emergency')], max_length=15)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_seen', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shepherd')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_sent',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Birthday', 'Birthday'), ('Suggestion/Complaint', 'Suggestion/Complaint')], max_length=50)),
                ('is_activated', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('time_sensitivity', models.CharField(choices=[('None', 'None'), ('1 DAY', '1 DAY')], max_length=15)),
                ('activator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activator', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_activated',),
            },
        ),
    ]
