# Generated by Django 4.2.1 on 2023-06-26 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_suggestioncomplaintmessage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_activated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='exposure_level',
            field=models.CharField(choices=[('general', 'general'), ('pastoral', 'pastoral'), ('all', 'all')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mode',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Suggestion/Complaint', 'Suggestion/Complaint'), ('Shepherd Report', 'Shepherd Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
