# Generated by Django 4.2.1 on 2023-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notification_date_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='category',
            field=models.CharField(choices=[('prayer_marathon', 'Prayer Marathon'), ('bible_reading', 'Bible Reading'), ('church_work', 'Church Work'), ('evangelism', 'Evangelism'), ('prophetic_vision', 'Prophetic Vision'), ('bio_data', 'Bio Data'), ('shepherd_report', 'Shepherd Report')], max_length=20),
        ),
    ]
