# Generated by Django 4.2.7 on 2023-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_notification_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='exposure_level',
            field=models.CharField(choices=[('general', 'general'), ('pastoral', 'pastoral'), ('project_management', 'project_management'), ('all', 'all')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mode',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Suggestion/Complaint', 'Suggestion/Complaint'), ('Shepherd Report', 'Shepherd Report'), ('Target Approval', 'Target Approval')], max_length=50),
        ),
    ]
