# Generated by Django 4.2.7 on 2023-12-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_development', '0004_shepherdreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shepherdreport',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shepherd'),
        ),
        migrations.AlterField(
            model_name='shepherdreport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
