# Generated by Django 4.2.7 on 2024-08-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaconate', '0003_treasuryrequest_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AddField(
            model_name='treasuryrequest',
            name='asset_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diaconate.assetcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treasuryrequest',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='Deadline for the request', null=True),
        ),
    ]
