# Generated by Django 4.2.7 on 2024-09-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaconate', '0004_alter_assetcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
