# Generated by Django 4.2.7 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaconate', '0005_alter_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('image', 'img'), ('video', 'video')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
        migrations.AddField(
            model_name='asset',
            name='files',
            field=models.ManyToManyField(blank=True, to='diaconate.assetfile'),
        ),
    ]
