# Generated by Django 4.2.7 on 2024-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaconate', '0008_remove_treasuryrequest_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryrequest',
            name='new_location',
            field=models.CharField(choices=[('Afaha-Ube House', 'Afaha-Ube House'), ('Bethel House', 'Bethel House'), ('Commonwealth House', 'Commonwealth House'), ('Shelter-Afrique Farmhouse', 'Shelter-Afrique Farmhouse'), ('The 3rd Floor', 'The 3rd Floor'), ('The Manse', 'The Manse'), ('UdoAbasi House', 'UdoAbasi House'), ('Udoette House', 'Udoette House'), ('Udomita Farmhouse', 'Udomita Farmhouse')], default='', max_length=1000),
        ),
    ]
