# Generated by Django 4.2.7 on 2024-12-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaconate', '0010_assetcategory_description_attribute_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='AssetAttribute',
        ),
    ]
