# Generated by Django 4.2.1 on 2023-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetic_vision', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propheticvision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
