# Generated by Django 4.2.7 on 2025-01-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unperplexed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('design', 'Design'), ('agriculture', 'Agriculture'), ('event_services', 'Event Seervices')], default='construction', max_length=100),
            preserve_default=False,
        ),
    ]
