# Generated by Django 5.1.6 on 2025-02-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unperplexed', '0002_worker_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('design', 'Design'), ('agriculture', 'Agriculture'), ('event_services', 'Event Services')], max_length=100),
        ),
    ]
