# Generated by Django 5.1.6 on 2025-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unperplexed', '0003_alter_worker_options_alter_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
