# Generated by Django 5.1.6 on 2025-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unperplexed', '0005_contract_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
