# Generated by Django 4.2.1 on 2023-05-19 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church_work', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchwork',
            name='last_active_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last active date'),
        ),
    ]
