# Generated by Django 4.2.7 on 2023-12-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_work', '0003_churchwork_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchwork',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
